name: Publish to PyPI

on:
  # Allow manual triggering
  workflow_dispatch:
    
  release:
    types: [ released, prereleased ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: MREYE-LUMC/actions/python-build@main
        with:
          artifact-name: dist
          artifact-path: "dist/"

  publish_to_pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: pypi

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: MREYE-LUMC/actions/python-publish@main
        with:
          tag: ${{ github.ref }}
          artifact-name: dist
          artifact-path: "dist/"